// Monta os graded readers franceses a partir das seções anotadas:
// valida lossless contra o texto-fonte, gera data/content/<id>.json e
// reconstrói o catálogo data/readers-fr.json.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const DATA = join(process.cwd(), 'data');
const FR = join(DATA, 'fr');

// Registro dos livros franceses (acrescente aqui os próximos).
const BOOKS = [
  {
    id: 10001,
    slug: 'le-garcon-qui-ne-pouvait-pas-dire-la-verite',
    title: 'Le Garçon Qui Ne Pouvait Pas Dire La Vérité',
    sectionPrefix: '_section-', // primeiro livro usou esse prefixo
    sections: 4,
    coverUrl: '/covers/23-covers.png',
  },
  {
    id: 10002,
    slug: 'l-endroit-heureux',
    title: "L'Endroit Heureux",
    sectionPrefix: '_10002-section-',
    sections: 4,
    coverUrl: '/covers/25-covers.png',
  },
  {
    id: 10003,
    slug: 'la-sage-femme',
    title: 'La Sage-Femme',
    sectionPrefix: '_10003-section-',
    sections: 4,
    coverUrl: '/covers/17-covers.png',
  },
  {
    id: 10004,
    slug: 'les-questions-d-anna',
    title: "Les Questions d'Anna",
    sectionPrefix: '_10004-section-',
    sections: 4,
    coverUrl: '/covers/26-covers.png',
  },
  {
    id: 10005,
    slug: 'coeur-froid',
    title: 'Cœur Froid',
    sectionPrefix: '_10005-section-',
    sections: 4,
    coverUrl: '/covers/11-covers.png',
  },
  {
    id: 10006,
    slug: 'bon-coeur-et-ses-quatre-amis',
    title: 'Bon Cœur et Ses Quatre Amis',
    sectionPrefix: '_10006-section-',
    sections: 4,
    coverUrl: '/covers/7-covers.png',
  },
  {
    id: 10007,
    slug: 'comment-la-meduse-a-perdu-sa-carapace',
    title: 'Comment La Méduse A Perdu Sa Carapace',
    sectionPrefix: '_10007-section-',
    sections: 4,
    coverUrl: '/covers/1-covers.png',
  },
  {
    id: 10008,
    slug: 'comme-romeo-et-juliette',
    title: 'Comme Roméo et Juliette',
    sectionPrefix: '_10008-section-',
    sections: 4,
    coverUrl: '/covers/24-covers.png',
  },
  {
    id: 10009,
    slug: 'un-bienfait-n-est-jamais-perdu',
    title: "Un Bienfait N'Est Jamais Perdu",
    sectionPrefix: '_10009-section-',
    sections: 4,
    coverUrl: '/covers/9-covers.png',
  },
  {
    id: 10010,
    slug: 'etoile-yeux-noirs-et-longs-bras',
    title: 'Étoile, Yeux Noirs et Longs Bras',
    sectionPrefix: '_10010-section-',
    sections: 4,
    coverUrl: '/covers/14-covers.png',
  },
  {
    id: 10011,
    slug: 'tete-forte-et-son-chien',
    title: 'Tête Forte et Son Chien',
    sectionPrefix: '_10011-section-',
    sections: 4,
    coverUrl: '/covers/8-covers.png',
  },
  {
    id: 10012,
    slug: 'l-oiseau-de-verite',
    title: "L'Oiseau de Vérité",
    sectionPrefix: '_10012-section-',
    sections: 4,
    coverUrl: '/covers/2-covers.png',
  },
  {
    id: 10013,
    slug: 'le-chien-qui-parlait-trop',
    title: 'Le Chien Qui Parlait Trop',
    sectionPrefix: '_10013-section-',
    sections: 4,
    coverUrl: '/covers/15-covers.png',
  },
  {
    id: 10014,
    slug: 'le-dragon',
    title: 'Le Dragon',
    sectionPrefix: '_10014-section-',
    sections: 4,
    coverUrl: '/covers/18-covers.png',
  },
  {
    id: 10015,
    slug: 'le-chien-de-feu-et-le-chien-bleu',
    title: 'Le Chien de Feu et le Chien Bleu',
    sectionPrefix: '_10015-section-',
    sections: 4,
    coverUrl: '/covers/10-covers.png',
  },
  {
    id: 10016,
    slug: 'les-quatre-garcons',
    title: 'Les Quatre Garçons',
    sectionPrefix: '_10016-section-',
    sections: 4,
    coverUrl: '/covers/3-covers.png',
  },
  {
    id: 10017,
    slug: 'la-maison-du-feu-noir',
    title: 'La Maison du Feu Noir',
    sectionPrefix: '_10017-section-',
    sections: 4,
    coverUrl: '/covers/4-covers.png',
  },
  {
    id: 10018,
    slug: 'la-petite-fille-qui-voulait-une-etoile',
    title: 'La Petite Fille Qui Voulait une Étoile',
    sectionPrefix: '_10018-section-',
    sections: 4,
    coverUrl: '/covers/22-covers.png',
  },
  {
    id: 10019,
    slug: 'la-petite-soeur',
    title: 'La Petite Sœur',
    sectionPrefix: '_10019-section-',
    sections: 4,
    coverUrl: '/covers/12-covers.png',
  },
  {
    id: 10020,
    slug: 'la-maison-magique',
    title: 'La Maison Magique',
    sectionPrefix: '_10020-section-',
    sections: 4,
    coverUrl: '/covers/21-covers.png',
  },
  {
    id: 10021,
    slug: 'le-lecteur-de-pensees',
    title: 'Le Lecteur de Pensées',
    sectionPrefix: '_10021-section-',
    sections: 4,
    coverUrl: '/covers/29-covers.png',
  },
  {
    id: 10022,
    slug: 'le-pauvre-homme-et-le-roi-des-corbeaux',
    title: 'Le Pauvre Homme et le Roi des Corbeaux',
    sectionPrefix: '_10022-section-',
    sections: 4,
    coverUrl: '/covers/5-covers.png',
  },
  {
    id: 10023,
    slug: 'la-princesse-de-la-tour',
    title: 'La Princesse de la Tour',
    sectionPrefix: '_10023-section-',
    sections: 4,
    coverUrl: '/covers/6-covers.png',
  },
  {
    id: 10024,
    slug: 'la-princesse-de-la-colline-de-verre',
    title: 'La Princesse de la Colline de Verre',
    sectionPrefix: '_10024-section-',
    sections: 4,
    coverUrl: '/covers/13-covers.png',
  },
  {
    id: 10025,
    slug: 'la-journaliste',
    title: 'La Journaliste',
    sectionPrefix: '_10025-section-',
    sections: 4,
    coverUrl: '/covers/30-covers.png',
  },
  {
    id: 10026,
    slug: 'l-histoire-de-miles',
    title: "L'Histoire de Miles",
    sectionPrefix: '_10026-section-',
    sections: 4,
    coverUrl: '/covers/28-covers.png',
  },
  {
    id: 10027,
    slug: 'la-conteuse-de-mur-blanc',
    title: 'La Conteuse de Mur Blanc',
    sectionPrefix: '_10027-section-',
    sections: 4,
    coverUrl: '/covers/20-covers.png',
  },
  {
    id: 10028,
    slug: 'le-voyageur',
    title: 'Le Voyageur',
    sectionPrefix: '_10028-section-',
    sections: 4,
    coverUrl: '/covers/27-covers.png',
  },
  {
    id: 10029,
    slug: 'les-deux-princes',
    title: 'Les Deux Princes',
    sectionPrefix: '_10029-section-',
    sections: 4,
    coverUrl: '/covers/16-covers.png',
  },
  {
    id: 10030,
    slug: 'cheveux-blancs-et-poil-noir',
    title: 'Cheveux Blancs et Poil Noir',
    sectionPrefix: '_10030-section-',
    sections: 4,
    coverUrl: '/covers/19-covers.png',
  },
  // ---- Nível 2 ----
  {
    id: 10031,
    slug: 'un-panier-plein-d-amour',
    title: "Un Panier Plein d'Amour",
    sectionPrefix: '_10031-section-',
    sections: 4,
    coverUrl: '/covers/49-covers.png',
    level: 2,
  },
  {
    id: 10032,
    slug: 'un-jour-qui-defie-la-raison',
    title: 'Un Jour Qui Défie la Raison',
    sectionPrefix: '_10032-section-',
    sections: 4,
    coverUrl: '/covers/53-covers.png',
    level: 2,
  },
  {
    id: 10033,
    slug: 'une-histoire-de-detective',
    title: 'Une Histoire de Détective',
    sectionPrefix: '_10033-section-',
    sections: 4,
    coverUrl: '/covers/40-covers.png',
    level: 2,
  },
  {
    id: 10034,
    slug: 'une-histoire-d-amour-presque-ordinaire',
    title: "Une Histoire d'Amour Presque Ordinaire",
    sectionPrefix: '_10034-section-',
    sections: 4,
    coverUrl: '/covers/54-covers.png',
    level: 2,
  },
  {
    id: 10035,
    slug: 'un-bon-conseil',
    title: 'Un Bon Conseil',
    sectionPrefix: '_10035-section-',
    sections: 4,
    coverUrl: '/covers/42-covers.png',
    level: 2,
  },
  {
    id: 10036,
    slug: 'une-soiree-etrange',
    title: 'Une Soirée Étrange',
    sectionPrefix: '_10036-section-',
    sections: 4,
    coverUrl: '/covers/46-covers.png',
    level: 2,
  },
  {
    id: 10037,
    slug: 'une-rencontre-du-troisieme-type',
    title: 'Une Rencontre du Troisième Type',
    sectionPrefix: '_10037-section-',
    sections: 4,
    coverUrl: '/covers/34-covers.png',
    level: 2,
  },
  {
    id: 10038,
    slug: 'ma-premiere-journee-d-adulte',
    title: "Ma Première Journée d'Adulte",
    sectionPrefix: '_10038-section-',
    sections: 4,
    coverUrl: '/covers/32-covers.png',
    level: 2,
  },
  {
    id: 10039,
    slug: 'quand-j-ai-touche-le-fond',
    title: "Quand J'ai Touché le Fond",
    sectionPrefix: '_10039-section-',
    sections: 4,
    coverUrl: '/covers/35-covers.png',
    level: 2,
  },
  {
    id: 10040,
    slug: 'sans-regrets',
    title: 'Sans Regrets',
    sectionPrefix: '_10040-section-',
    sections: 4,
    coverUrl: '/covers/45-covers.png',
    level: 2,
  },
  {
    id: 10041,
    slug: 'tristesse-et-serendipite',
    title: 'Tristesse et Sérendipité',
    sectionPrefix: '_10041-section-',
    sections: 4,
    coverUrl: '/covers/41-covers.png',
    level: 2,
  },
  {
    id: 10042,
    slug: 'le-jour-de-chance-de-sept',
    title: 'Le Jour de Chance de Sept',
    sectionPrefix: '_10042-section-',
    sections: 4,
    coverUrl: '/covers/50-covers.png',
    level: 2,
  },
  {
    id: 10043,
    slug: 'des-amants-sous-une-mauvaise-etoile',
    title: 'Des Amants Sous une Mauvaise Étoile',
    sectionPrefix: '_10043-section-',
    sections: 4,
    coverUrl: '/covers/56-covers.png',
    level: 2,
  },
  {
    id: 10044,
    slug: 'le-soleil-en-capricorne',
    title: 'Le Soleil en Capricorne',
    sectionPrefix: '_10044-section-',
    sections: 4,
    coverUrl: '/covers/51-covers.png',
    level: 2,
  },
  {
    id: 10045,
    slug: 'le-chien-bleu',
    title: 'Le Chien Bleu',
    sectionPrefix: '_10045-section-',
    sections: 4,
    coverUrl: '/covers/55-covers.png',
    level: 2,
  },
  {
    id: 10046,
    slug: 'le-bon-cote-de-l-ennui',
    title: "Le Bon Côté de l'Ennui",
    sectionPrefix: '_10046-section-',
    sections: 4,
    coverUrl: '/covers/59-covers.png',
    level: 2,
  },
  {
    id: 10047,
    slug: 'le-reve',
    title: 'Le Rêve',
    sectionPrefix: '_10047-section-',
    sections: 4,
    coverUrl: '/covers/38-covers.png',
    level: 2,
  },
  {
    id: 10048,
    slug: 'le-musee-de-la-terre',
    title: 'Le Musée de la Terre',
    sectionPrefix: '_10048-section-',
    sections: 4,
    coverUrl: '/covers/52-covers.png',
    level: 2,
  },
  {
    id: 10049,
    slug: 'l-annee-magique',
    title: "L'Année Magique",
    sectionPrefix: '_10049-section-',
    sections: 4,
    coverUrl: '/covers/33-covers.png',
    level: 2,
  },
  {
    id: 10050,
    slug: 'la-vieille-poupee',
    title: 'La Vieille Poupée',
    sectionPrefix: '_10050-section-',
    sections: 4,
    coverUrl: '/covers/57-covers.png',
    level: 2,
  },
  {
    id: 10051,
    slug: 'la-vieille-maison-sur-la-colline',
    title: 'La Vieille Maison sur la Colline',
    sectionPrefix: '_10051-section-',
    sections: 4,
    coverUrl: '/covers/39-covers.png',
    level: 2,
  },
  {
    id: 10052,
    slug: 'la-bibliotheque-de-la-patience',
    title: 'La Bibliothèque de la Patience',
    sectionPrefix: '_10052-section-',
    sections: 4,
    coverUrl: '/covers/47-covers.png',
    level: 2,
  },
  {
    id: 10053,
    slug: 'la-nuit-la-plus-effrayante-de-ma-vie',
    title: 'La Nuit la Plus Effrayante de Ma Vie',
    sectionPrefix: '_10053-section-',
    sections: 4,
    coverUrl: '/covers/37-covers.png',
    level: 2,
  },
  {
    id: 10054,
    slug: 'le-secret',
    title: 'Le Secret',
    sectionPrefix: '_10054-section-',
    sections: 4,
    coverUrl: '/covers/31-covers.png',
    level: 2,
  },
  {
    id: 10055,
    slug: 'l-histoire-d-un-meurtre',
    title: "L'Histoire d'un Meurtre",
    sectionPrefix: '_10055-section-',
    sections: 4,
    coverUrl: '/covers/36-covers.png',
    level: 2,
  },
  {
    id: 10056,
    slug: 'l-histoire-de-star',
    title: "L'Histoire de Star",
    sectionPrefix: '_10056-section-',
    sections: 4,
    coverUrl: '/covers/43-covers.png',
    level: 2,
  },
  {
    id: 10057,
    slug: 'le-voeu',
    title: 'Le Vœu',
    sectionPrefix: '_10057-section-',
    sections: 4,
    coverUrl: '/covers/58-covers.png',
    level: 2,
  },
  {
    id: 10058,
    slug: 'sois-fidele-a-toi-meme',
    title: 'Sois Fidèle à Toi-Même',
    sectionPrefix: '_10058-section-',
    sections: 4,
    coverUrl: '/covers/60-covers.png',
    level: 2,
  },
  {
    id: 10059,
    slug: 'un-amour-d-hiver',
    title: "Un Amour d'Hiver",
    sectionPrefix: '_10059-section-',
    sections: 4,
    coverUrl: '/covers/44-covers.png',
    level: 2,
  },
  {
    id: 10060,
    slug: 'avec-un-peu-d-aide-de-nos-amis',
    title: 'Avec un Peu d\'Aide de Nos Amis',
    sectionPrefix: '_10060-section-',
    sections: 4,
    coverUrl: '/covers/48-covers.png',
    level: 2,
  },
  {
    id: 10061,
    slug: 'une-lettre-au-pere-noel',
    title: 'Une Lettre au Père Noël',
    sectionPrefix: '_10061-section-',
    sections: 4,
    coverUrl: '/covers/89-covers.png',
    level: 3,
  },
  {
    id: 10062,
    slug: 'une-nouvelle-ame',
    title: 'Une Nouvelle Âme',
    sectionPrefix: '_10062-section-',
    sections: 4,
    coverUrl: '/covers/90-covers.png',
    level: 3,
  },
  {
    id: 10063,
    slug: 'une-mer-de-tenebres',
    title: 'Une Mer de Ténèbres',
    sectionPrefix: '_10063-section-',
    sections: 4,
    coverUrl: '/covers/65-covers.png',
    level: 3,
  },
  {
    id: 10064,
    slug: 'une-histoire-d-amour',
    title: "Une Histoire d'Amour",
    sectionPrefix: '_10064-section-',
    sections: 4,
    coverUrl: '/covers/80-covers.png',
    level: 3,
  },
  {
    id: 10065,
    slug: 'alice-au-mauvais-etage',
    title: 'Alice au Mauvais Étage',
    sectionPrefix: '_10065-section-',
    sections: 4,
    coverUrl: '/covers/66-covers.png',
    level: 3,
  },
  {
    id: 10066,
    slug: 'de-grands-reves',
    title: 'De Grands Rêves',
    sectionPrefix: '_10066-section-',
    sections: 4,
    coverUrl: '/covers/83-covers.png',
    level: 3,
  },
  {
    id: 10067,
    slug: 'trouver-mon-ame',
    title: 'Trouver Mon Âme',
    sectionPrefix: '_10067-section-',
    sections: 4,
    coverUrl: '/covers/62-covers.png',
    level: 3,
  },
  {
    id: 10068,
    slug: 'je-sais-que-je-ne-sais-rien',
    title: 'Je Sais Que Je Ne Sais Rien',
    sectionPrefix: '_10068-section-',
    sections: 4,
    coverUrl: '/covers/72-covers.png',
    level: 3,
  },
  {
    id: 10069,
    slug: 'ete-hiver-printemps-et-automne',
    title: 'Été-Hiver-Printemps et Automne',
    sectionPrefix: '_10069-section-',
    sections: 4,
    coverUrl: '/covers/78-covers.png',
    level: 3,
  },
  {
    id: 10070,
    slug: 'la-fete-d-anniversaire',
    title: "La Fête d'Anniversaire",
    sectionPrefix: '_10070-section-',
    sections: 4,
    coverUrl: '/covers/61-covers.png',
    level: 3,
  },
  {
    id: 10071,
    slug: 'le-club-de-cuisine',
    title: 'Le Club de Cuisine',
    sectionPrefix: '_10071-section-',
    sections: 4,
    coverUrl: '/covers/64-covers.png',
    level: 3,
  },
  {
    id: 10072,
    slug: 'le-voisin-grincheux',
    title: 'Le Voisin Grincheux',
    sectionPrefix: '_10072-section-',
    sections: 4,
    coverUrl: '/covers/67-covers.png',
    level: 3,
  },
  {
    id: 10073,
    slug: 'le-savant-fou',
    title: 'Le Savant Fou',
    sectionPrefix: '_10073-section-',
    sections: 4,
    coverUrl: '/covers/68-covers.png',
    level: 3,
  },
  {
    id: 10074,
    slug: 'la-galerie-sombre',
    title: 'La Galerie Sombre',
    sectionPrefix: '_10074-section-',
    sections: 4,
    coverUrl: '/covers/76-covers.png',
    level: 3,
  },
  {
    id: 10075,
    slug: 'le-sosie',
    title: 'Le Sosie',
    sectionPrefix: '_10075-section-',
    sections: 4,
    coverUrl: '/covers/88-covers.png',
    level: 3,
  },
  {
    id: 10076,
    slug: 'le-luddite',
    title: 'Le Luddite',
    sectionPrefix: '_10076-section-',
    sections: 4,
    coverUrl: '/covers/77-covers.png',
    level: 3,
  },
  {
    id: 10077,
    slug: 'le-correspondant-sur-mars',
    title: 'Le Correspondant sur Mars',
    sectionPrefix: '_10077-section-',
    sections: 4,
    coverUrl: '/covers/75-covers.png',
    level: 3,
  },
  {
    id: 10078,
    slug: 'la-reunion',
    title: 'La Réunion',
    sectionPrefix: '_10078-section-',
    sections: 4,
    coverUrl: '/covers/81-covers.png',
    level: 3,
  },
  {
    id: 10079,
    slug: 'le-miroir',
    title: 'Le Miroir',
    sectionPrefix: '_10079-section-',
    sections: 4,
    coverUrl: '/covers/63-covers.png',
    level: 3,
  },
  {
    id: 10080,
    slug: 'l-academie-des-cauchemars',
    title: 'L\'Académie des Cauchemars',
    sectionPrefix: '_10080-section-',
    sections: 4,
    coverUrl: '/covers/73-covers.png',
    level: 3,
  },
  {
    id: 10081,
    slug: 'la-carte-postale-1',
    title: 'La Carte Postale (1)',
    sectionPrefix: '_10081-section-',
    sections: 4,
    coverUrl: '/covers/85-covers.png',
    level: 3,
  },
  {
    id: 10082,
    slug: 'la-carte-postale-2',
    title: 'La Carte Postale (2)',
    sectionPrefix: '_10082-section-',
    sections: 4,
    coverUrl: '/covers/86-covers.png',
    level: 3,
  },
  {
    id: 10083,
    slug: 'la-carte-postale-3',
    title: 'La Carte Postale (3)',
    sectionPrefix: '_10083-section-',
    sections: 4,
    coverUrl: '/covers/87-covers.png',
    level: 3,
  },
  {
    id: 10084,
    slug: 'le-pouvoir-de-l-amour',
    title: 'Le Pouvoir de l\'Amour',
    sectionPrefix: '_10084-section-',
    sections: 4,
    coverUrl: '/covers/69-covers.png',
    level: 3,
  },
  {
    id: 10085,
    slug: 'la-riviere-de-la-vie',
    title: 'La Rivière de la Vie',
    sectionPrefix: '_10085-section-',
    sections: 4,
    coverUrl: '/covers/71-covers.png',
    level: 3,
  },
  {
    id: 10086,
    slug: 'l-attraction-au-bord-de-la-route',
    title: 'L\'Attraction au Bord de la Route',
    sectionPrefix: '_10086-section-',
    sections: 4,
    coverUrl: '/covers/79-covers.png',
    level: 3,
  },
  {
    id: 10087,
    slug: 'la-colocataire',
    title: 'La Colocataire',
    sectionPrefix: '_10087-section-',
    sections: 4,
    coverUrl: '/covers/74-covers.png',
    level: 3,
  },
  {
    id: 10088,
    slug: 'la-guerre-de-l-orthographe',
    title: 'La Guerre de l\'Orthographe',
    sectionPrefix: '_10088-section-',
    sections: 4,
    coverUrl: '/covers/70-covers.png',
    level: 3,
  },
  {
    id: 10089,
    slug: 'l-histoire-d-une-histoire',
    title: 'L\'Histoire d\'une Histoire',
    sectionPrefix: '_10089-section-',
    sections: 4,
    coverUrl: '/covers/84-covers.png',
    level: 3,
  },
  {
    id: 10090,
    slug: 'le-blagueur',
    title: 'Le Blagueur',
    sectionPrefix: '_10090-section-',
    sections: 4,
    coverUrl: '/covers/82-covers.png',
    level: 3,
  },
  // ---- Nível 4 ----
  {
    id: 10091,
    slug: 'un-homme-d-habitudes',
    title: "Un Homme d'Habitudes",
    sectionPrefix: '_10091-section-',
    sections: 4,
    coverUrl: '/covers/102-covers.png',
    level: 4,
  },
  {
    id: 10092,
    slug: 'un-cours-de-meditation',
    title: 'Un Cours de Méditation',
    sectionPrefix: '_10092-section-',
    sections: 4,
    coverUrl: '/covers/97-covers.png',
    level: 4,
  },
  {
    id: 10093,
    slug: 'une-nouvelle-vie-vous-attend',
    title: 'Une Nouvelle Vie Vous Attend',
    sectionPrefix: '_10093-section-',
    sections: 4,
    coverUrl: '/covers/96-covers.png',
    level: 4,
  },
  {
    id: 10094,
    slug: 'invasion-extraterrestre',
    title: 'Invasion Extraterrestre',
    sectionPrefix: '_10094-section-',
    sections: 4,
    coverUrl: '/covers/99-covers.png',
    level: 4,
  },
  {
    id: 10095,
    slug: 'presque-poete',
    title: 'Presque Poète',
    sectionPrefix: '_10095-section-',
    sections: 4,
    coverUrl: '/covers/105-covers.png',
    level: 4,
  },
  {
    id: 10096,
    slug: 'presque-ingenieure',
    title: 'Presque Ingénieure',
    sectionPrefix: '_10096-section-',
    sections: 4,
    coverUrl: '/covers/109-covers.png',
    level: 4,
  },
  {
    id: 10097,
    slug: 'une-amitie-extraterrestre',
    title: 'Une Amitié Extraterrestre',
    sectionPrefix: '_10097-section-',
    sections: 4,
    coverUrl: '/covers/114-covers.png',
    level: 4,
  },
  {
    id: 10098,
    slug: 'quelle-poisse',
    title: 'Quelle Poisse !',
    sectionPrefix: '_10098-section-',
    sections: 4,
    coverUrl: '/covers/94-covers.png',
    level: 4,
  },
  {
    id: 10099,
    slug: 'l-avenir-et-le-present',
    title: "L'Avenir et le Présent",
    sectionPrefix: '_10099-section-',
    sections: 4,
    coverUrl: '/covers/103-covers.png',
    level: 4,
  },
  {
    id: 10100,
    slug: 'la-fievre-de-l-imagination',
    title: "La Fièvre de l'Imagination",
    sectionPrefix: '_10100-section-',
    sections: 4,
    coverUrl: '/covers/92-covers.png',
    level: 4,
  },
  {
    id: 10101,
    slug: 'lettres-du-futur',
    title: 'Lettres du Futur',
    sectionPrefix: '_10101-section-',
    sections: 4,
    coverUrl: '/covers/106-covers.png',
    level: 4,
  },
  {
    id: 10102,
    slug: 'vider-son-sac',
    title: 'Vider son Sac',
    sectionPrefix: '_10102-section-',
    sections: 4,
    coverUrl: '/covers/100-covers.png',
    level: 4,
  },
  {
    id: 10103,
    slug: 'univers-parallele',
    title: 'Univers Parallèle',
    sectionPrefix: '_10103-section-',
    sections: 4,
    coverUrl: '/covers/111-covers.png',
    level: 4,
  },
  {
    id: 10104,
    slug: 'pareidolie',
    title: 'Paréidolie',
    sectionPrefix: '_10104-section-',
    sections: 4,
    coverUrl: '/covers/98-covers.png',
    level: 4,
  },
  {
    id: 10105,
    slug: 'pygmalion',
    title: 'Pygmalion',
    sectionPrefix: '_10105-section-',
    sections: 4,
    coverUrl: '/covers/104-covers.png',
    level: 4,
  },
];

const WORD_RE = /[a-zà-ÿœ]+(?:['’][a-zà-ÿœ]+)*/gi;
const catalogue = [];

for (const book of BOOKS) {
  const sectionFiles = Array.from(
    { length: book.sections },
    (_, i) => join(FR, `${book.sectionPrefix}${i + 1}.json`)
  );
  if (!sectionFiles.every((f) => existsSync(f))) {
    console.log(`(${book.slug}: seções incompletas — pulado)`);
    continue;
  }
  const source = readFileSync(join(FR, `${book.slug}.txt`), 'utf8');
  const paragraphs = source
    .split(/\r?\n\r?\n+/)
    .map((p) => p.trim().replace(/\r?\n/g, ' '))
    .filter(Boolean);
  const expected = paragraphs.join('');

  const tokens = [];
  for (const f of sectionFiles) tokens.push(...JSON.parse(readFileSync(f, 'utf8')));

  // Normalização defensiva + validações
  for (const t of tokens) {
    if (t.translation && !Array.isArray(t.translation.tips)) t.translation.tips = [];
  }
  const concat = tokens.map((t) => t.text).join('');
  if (concat !== expected) {
    let d = 0;
    while (d < Math.min(concat.length, expected.length) && concat[d] === expected[d]) d++;
    console.error(`${book.slug}: LOSSLESS FALHOU no char ${d}:`);
    console.error('  esperado: ' + JSON.stringify(expected.slice(Math.max(0, d - 40), d + 40)));
    console.error('  obtido:   ' + JSON.stringify(concat.slice(Math.max(0, d - 40), d + 40)));
    process.exit(1);
  }
  const newLines = tokens.filter((t) => t.newLine).length;
  if (newLines !== paragraphs.length) {
    console.error(`${book.slug}: paragrafos esperado ${paragraphs.length}, obtido ${newLines}`);
    process.exit(1);
  }

  writeFileSync(
    join(DATA, 'content', `${book.id}.json`),
    JSON.stringify({ id: book.id, total: tokens.length, tokens }, null, 0)
  );

  const words = expected.toLowerCase().match(WORD_RE) ?? [];
  const uniq = new Set(words);
  const withTr = tokens.filter((t) => t.translation).length;
  const withTips = tokens.filter((t) => t.translation?.tips?.length > 0).length;
  const expl = tokens
    .flatMap((t) => t.translation?.tips ?? [])
    .filter((x) => x.explanation).length;

  catalogue.push({
    id: book.id,
    title: book.title,
    sampleText: expected.slice(0, 400),
    level: book.level ?? 1,
    coverUrl: book.coverUrl,
    position: 0,
    times: 0,
    listeningTimes: 0,
    narrator: 'Camille',
    audioDuration: Math.round((words.length / 130) * 10) / 10,
    published: true,
    // Espelha o original: só os 3 primeiros readers do nível são tryout.
    tryout: book.id <= 10003,
    score: null,
    uniqueWordsNumber: uniq.size,
    lang: 'fr',
  });

  console.log(
    `${book.slug}: OK lossless ✓ | tokens ${tokens.length} | trad ${withTr} | tips ${withTips} | expl ${expl} | palavras ${words.length} | unicas ${uniq.size} | TTR ${(uniq.size / words.length).toFixed(2)}`
  );
}

writeFileSync(join(DATA, 'readers-fr.json'), JSON.stringify(catalogue, null, 0));
console.log(`catalogo fr: ${catalogue.length} livros`);
